// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7Xrv74mWYqTpb-qnCQ_xhgD5e5D6qmk',
    appId: '1:428361774704:android:8b430e7ca2b504452366b5',
    messagingSenderId: '428361774704',
    projectId: 'note-management-app-7a5cc',
    storageBucket: 'note-management-app-7a5cc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLp96bmKVJrh8oixEj9QdHpPiS3UoWPjA',
    appId: '1:428361774704:ios:517e0b3143f9d4e82366b5',
    messagingSenderId: '428361774704',
    projectId: 'note-management-app-7a5cc',
    storageBucket: 'note-management-app-7a5cc.firebasestorage.app',
    iosBundleId: 'com.example.notesManagementApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRJsWEAHvFt1MPvukt4KmJFklMnkqkbs',
    appId: '1:428361774704:web:759c1e2b6205659a2366b5',
    messagingSenderId: '428361774704',
    projectId: 'note-management-app-7a5cc',
    authDomain: 'note-management-app-7a5cc.firebaseapp.com',
    storageBucket: 'note-management-app-7a5cc.firebasestorage.app',
  );
}
